---
- name: Add key
  tags: install
  apt_key:
   keyserver: keyserver.ubuntu.com
   id: EA312927

- name: Add repo
  tags: install
  apt_repository:
   repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
   state: present

- name: Install mongo
  tags: install
  apt:
   name: mongodb-org
   update_cache: true

- name: restart mongod sevice
  service: name=mongod state=started daemon-reload=true

- name: Enable and run as a service
  tags: install
  systemd:
   name: mongod
   enabled: true
   state: started
